<?php

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../PHPMailUnit/PHPMailUnit.php';

//From PEAR Mail extension
require_once 'Mail.php';

/**
 * Test class for PHPMailUnit.
 * Generated by PHPUnit on 2010-09-23 at 21:56:31.
 */
class PHPMailUnitTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        PHPMailUnit::setUp();
    }

    protected function tearDown() {
        PHPMailUnit::tearDown();
    }

    public function testGetLastMail() {
        $mail = Mail::factory('smtp', array('host' => 'localhost',
                                            'port' => 3535));
        $r = $mail->send(array('recipient@test.com'),
                        array('From' => 'sender@test.com',
                            'Subject' => 'Test subject'),
                        'Body content');

        $mail = PHPMailUnit::getLastMail();

        $this->assertNotNull($mail);
        $this->assertTrue($mail->from === 'sender@test.com');
        $this->assertTrue($mail->subject === 'Test subject',
                          "Subject <".$mail->subject."> != <Test subject>");
    }

}

?>
